### ISSUE TITLE
Readme is hard to understand

### ISSUE THREAD

**Issue by LudwikJaniuk** [DrInfiniteExplorer/enumerable#2]
The readme is a screenfull of text, which makes it harder to comprehend. I think this could be improved, maybe divide it into sections, add code examples, etc?

PS: Hej, det är Ludvig fråm C++ Sweden. Det var kul att träffas!

**Comment by DrInfiniteExplorer** [comment]
Haha, Hi, didn't notice the issue, guess I've got to turn on email-notifs somewhere!

Yep, it was written in a haste to have at least something. If you have suggestions of format/layout/structure that would be welcome! :)

**Comment by LudwikJaniuk** [comment]
I'd love to add some, but would need to understand the project better first, so it's kind of a chicken-and-egg problem ;)

Do you have any code samples/examples where I could see "enumerable" in action?

**Comment by DrInfiniteExplorer** [comment]
https://github.com/DrInfiniteExplorer/enumerable/blob/master/test/main.cpp contains lots if simple uses. It was written to test the functions while formulating the core of the library. Now I'm moving to writing google-tests of stuff, eventually everything will migrate into a google test.
I'm still lacking clear examples of where the library would be useful. When I could focus entierly on the lib I had many use cases in mind, but not anylonger.
Another library I'm working on will eventually be partially rewritten to make heavy use of it, at that point there will be lots of uses for the lib.
I sent you an email about IM's btw.

**Comment by DrInfiniteExplorer** [comment]
Skeleton for readme in place, closing issue for now. Reopen if unsatisfactory, or create new issue for specific issues related to the readme.
